#! /bin/sh
## -*- mode: sh -*-
set -e

uname_S=$(uname -s 2>/dev/null || echo not)

# If we're running in a terminal and want interactive docker
# Specifically "is there a STDIN file descriptor"
if [ -t 0 ]; then
    : "${DOCKER_RUN_INTERACTIVE_OPTS:=--tty --interactive}"
fi



if [ "${uname_S}" = "Darwin" ]; then
    # This stops macos from copying resource forks into thigns like tar
    export COPYFILE_DISABLE=true
fi


echo "Building the docker image. This could take a few minutes."
docker build -q -t fabmo/docker .
# We do want word splitting since there are multiple options here
# shellcheck disable=SC2086   
docker run --rm $DOCKER_RUN_INTERACTIVE_OPTS \
        -v $(pwd):/fabmo  \
       --mount type=volume,source=opt-fabmo,destination=/opt/fabmo,consistency=delegated \
       -p 8411:80 \
       fabmo/docker $*


exit 0
