/* eslint-disable no-undef */
/*
 * Canned-cuts controller — pendant-side state machine.
 *
 * Holds the currently active cut type + parameter set, exposes adjust /
 * commit operations to device adapters, and emits state events so a
 * future dashboard UI or pendant LCD can render the current params.
 *
 * The actual G-code is generated by runtime/manual/cannedCuts/ (pure).
 * This module is the *coordination* layer: it sources the current
 * machine position at commit time, writes the G-code to a temp file,
 * and submits it to the engine via machine.runFile().
 *
 * State machine:
 *   idle      → user is not in cut mode; pendant jogs/nudges normally
 *   active    → cut mode entered; params adjustable, READY to commit
 *   executing → cut submitted; ignore further inputs until machine idle
 *
 * Transitions:
 *   toggle(): idle ↔ active                 (LSTICK on F310)
 *   adjustParam(name, delta): active only
 *   commit(): active → executing            (RT on F310)
 *   (on machine idle after executing): executing → active
 */

var fs = require("fs");
var os = require("os");
var path = require("path");
var EventEmitter = require("events").EventEmitter;
var util = require("util");

var log = require("../log").logger("cannedCuts");
var cuts = require("../runtime/manual/cannedCuts");

var DEFAULT_PARAMS = {
    circular_bore: {
        diameter: 0.5,
        depth: 0.25,
        plungePerPass: 0.125,
        cutterDiameter: 0.25,
        feedRateXY: 60,
        feedRateZ: 30,
        safeZ: 0.5,
        mode: "pocket",
        pocketOverlap: 0.5,
        direction: "cw",
    },
};

// Increments for adjust operations. Tunable per param; pendant maps
// physical inputs (D-pad, wheel) onto these names.
var ADJUST_STEPS = {
    diameter: 0.0625,        // 1/16"
    depth: 0.0625,
    plungePerPass: 0.0625,
    cutterDiameter: 0.0625,
};

// Hard bounds — prevent obvious bad inputs (negative diameter, etc.).
var BOUNDS = {
    diameter: [0.0625, 12],
    depth: [0.01, 4],
    plungePerPass: [0.01, 0.5],
    cutterDiameter: [0.0625, 1.0],
};

function clamp(v, lo, hi) {
    if (v < lo) return lo;
    if (v > hi) return hi;
    return v;
}

function CannedCutsController(machine) {
    EventEmitter.call(this);
    this.machine = machine;
    this.state = "idle";              // idle | active | executing
    this.cutType = "circular_bore";   // only one for the prototype
    this.params = Object.assign({}, DEFAULT_PARAMS[this.cutType]);
    this._lastTempFile = null;

    // While executing, watch machine state for return to idle so we
    // can transition back to "active" automatically.
    this._statusListener = this._onMachineStatus.bind(this);
    if (this.machine && typeof this.machine.on === "function") {
        this.machine.on("status", this._statusListener);
    }
}
util.inherits(CannedCutsController, EventEmitter);

CannedCutsController.prototype.close = function () {
    if (this.machine && typeof this.machine.removeListener === "function") {
        this.machine.removeListener("status", this._statusListener);
    }
};

CannedCutsController.prototype._emitState = function (reason) {
    var payload = {
        state: this.state,
        cutType: this.cutType,
        params: Object.assign({}, this.params),
        reason: reason || null,
    };
    this.emit("canned_cut_state", payload);
};

CannedCutsController.prototype.toggle = function () {
    if (this.state === "executing") {
        log.debug("cannedCuts: toggle ignored, cut in progress");
        return;
    }
    if (this.state === "idle") {
        this.state = "active";
        log.info("cannedCuts: entered " + this.cutType + " mode; params=" +
                 JSON.stringify(this.params));
        this._emitState("enter");
    } else {
        this.state = "idle";
        log.info("cannedCuts: exited cut mode");
        this._emitState("exit");
    }
};

CannedCutsController.prototype.adjustParam = function (name, delta) {
    if (this.state !== "active") {
        log.debug("cannedCuts: adjustParam ignored, state=" + this.state);
        return;
    }
    if (!(name in this.params)) {
        log.warn("cannedCuts: adjustParam unknown param '" + name + "'");
        return;
    }
    var step = ADJUST_STEPS[name];
    if (step === undefined) {
        log.warn("cannedCuts: adjustParam no step defined for '" + name + "'");
        return;
    }
    var newVal = this.params[name] + step * delta;
    var bound = BOUNDS[name];
    if (bound) newVal = clamp(newVal, bound[0], bound[1]);
    this.params[name] = Math.round(newVal * 10000) / 10000;  // snap to 4dp
    log.debug("cannedCuts: " + name + " = " + this.params[name]);
    this._emitState("adjust:" + name);
};

CannedCutsController.prototype.setParam = function (name, value) {
    if (!(name in this.params)) return;
    var bound = BOUNDS[name];
    if (bound) value = clamp(value, bound[0], bound[1]);
    this.params[name] = value;
    this._emitState("set:" + name);
};

CannedCutsController.prototype.cancel = function () {
    if (this.state === "executing") {
        log.debug("cannedCuts: cancel ignored, cut in progress");
        return;
    }
    this.state = "idle";
    log.info("cannedCuts: cancelled");
    this._emitState("cancel");
};

CannedCutsController.prototype._readCurrentPosition = function () {
    var st = this.machine && this.machine.status;
    if (!st) return null;
    var x = st.posx;
    var y = st.posy;
    var z = st.posz;
    if (x === undefined || y === undefined || z === undefined) return null;
    return { x: x, y: y, z: z };
};

CannedCutsController.prototype.commit = function () {
    if (this.state !== "active") {
        log.warn("cannedCuts: commit ignored, state=" + this.state);
        return { ok: false, reason: "not_active" };
    }
    var pos = this._readCurrentPosition();
    if (!pos) {
        log.warn("cannedCuts: commit failed, no position available");
        return { ok: false, reason: "no_position" };
    }

    var generated;
    try {
        if (this.cutType === "circular_bore") {
            generated = cuts.circularBore(Object.assign({}, this.params, {
                center: { x: pos.x, y: pos.y },
                startZ: pos.z,
            }));
        } else {
            throw new Error("unknown cut type: " + this.cutType);
        }
    } catch (e) {
        log.warn("cannedCuts: commit generation failed: " + e.message);
        return { ok: false, reason: "generation_failed", error: e.message };
    }

    // Write the G-code to a temp file and ask the machine to run it.
    // Using a temp file matches the macros path — the engine accepts a
    // file path via runFile() which goes through interlock pre-scan and
    // proper runtime hand-off.
    var tmpDir = path.join(os.tmpdir(), "fabmo-canned-cuts");
    try {
        if (!fs.existsSync(tmpDir)) fs.mkdirSync(tmpDir, { recursive: true });
    } catch (e) {
        log.warn("cannedCuts: tmp dir create failed: " + e.message);
        return { ok: false, reason: "tmpdir_failed", error: e.message };
    }
    var fname = path.join(tmpDir,
        "canned-" + this.cutType + "-" + Date.now() + ".nc");
    try {
        fs.writeFileSync(fname, generated.gcode.join("\n") + "\n");
    } catch (e) {
        log.warn("cannedCuts: tmp file write failed: " + e.message);
        return { ok: false, reason: "tmpfile_write_failed", error: e.message };
    }

    log.info("cannedCuts: committing " + this.cutType +
             " at (" + pos.x.toFixed(3) + ", " + pos.y.toFixed(3) +
             ") tmpFile=" + fname +
             " summary=" + JSON.stringify(generated.summary));

    this._lastTempFile = fname;
    this.state = "executing";
    this._emitState("commit");

    try {
        // bypassInterlock=true: operator-driven canned move, same
        // privilege level as a pendant macro press.
        this.machine.runFile(fname, true);
    } catch (e) {
        log.warn("cannedCuts: runFile failed: " + e.message);
        this.state = "active";
        this._emitState("error:run_failed");
        return { ok: false, reason: "run_failed", error: e.message };
    }
    return { ok: true, summary: generated.summary, file: fname };
};

CannedCutsController.prototype._onMachineStatus = function (status) {
    if (this.state !== "executing") return;
    if (!status) return;
    // Machine drops back to "idle" when the file is done. The pendant
    // controller transitions back to "active" so the user can adjust
    // params + commit another cut without re-toggling mode.
    if (status.state === "idle") {
        this.state = "active";
        log.info("cannedCuts: execution complete");
        this._emitState("done");
    }
};

module.exports = {
    create: function (machine) { return new CannedCutsController(machine); },
    CannedCutsController: CannedCutsController,
    DEFAULT_PARAMS: DEFAULT_PARAMS,
    BOUNDS: BOUNDS,
    ADJUST_STEPS: ADJUST_STEPS,
};
