/* eslint-disable no-undef */
/*
 * Canned-cuts controller — pendant-side state machine.
 *
 * Holds the currently active cut type + parameter set, exposes adjust /
 * commit operations to device adapters, and emits state events so a
 * future dashboard UI or pendant LCD can render the current params.
 *
 * The actual G-code is generated by runtime/manual/toolbox/ (pure).
 * This module is the *coordination* layer: it sources the current
 * machine position at commit time, writes the G-code to a temp file,
 * and submits it to the engine via machine.runFile().
 *
 * State machine:
 *   idle      → user is not in cut mode; pendant jogs/nudges normally
 *   active    → cut mode entered; params adjustable, READY to commit
 *   executing → cut submitted; ignore further inputs until machine idle
 *
 * Transitions:
 *   toggle(): idle ↔ active                 (LSTICK on F310)
 *   adjustParam(name, delta): active only
 *   commit(): active → executing            (RT on F310)
 *   (on machine idle after executing): executing → active
 */

var fs = require("fs");
var os = require("os");
var path = require("path");
var EventEmitter = require("events").EventEmitter;
var util = require("util");

var log = require("../log").logger("toolbox");
var cuts = require("../runtime/manual/toolbox");
var actions = require("./actions");

var DEFAULT_PARAMS = {
    circular_bore: {
        diameter: 0.5,
        depth: 0.25,
        plungePerPass: 0.125,
        cutterDiameter: 0.25,
        feedRateXY: 60,
        feedRateZ: 30,
        safeZ: 0.5,
        mode: "pocket",
        pocketOverlap: 0.5,
        direction: "cw",
        // plungeFrom controls the Z reference used for the cut:
        //   "zero"   → cut top = Z0, bottom = -depth (typical "Z0 at
        //              material top" workflow)
        //   "height" → cut top = plungeHeight, bottom = plungeHeight -
        //              depth (operator types or jogs in an absolute Z)
        plungeFrom: "zero",
        plungeHeight: 0,
    },
    straight_line: {
        // Cut extends from current bit position in the +X/+Y quadrant.
        // angleDeg 0 = pure +X, 90 = pure +Y, 45 = NE diagonal.
        length: 4,
        angleDeg: 0,
        depth: 0.25,
        plungePerPass: 0.125,
        cutterDiameter: 0.25,
        feedRateXY: 60,
        feedRateZ: 30,
        safeZ: 0.5,
        plungeFrom: "zero",
        plungeHeight: 0,
    },
    planer: {
        // Rectangular raster planing. width × length area starting at
        // the current bit position; length is along grainDeg, width is
        // perpendicular (rotated +90° CCW from grain).
        width: 4,
        length: 4,
        depth: 0.05,
        plungePerPass: 0.05,
        cutterDiameter: 0.25,
        stepoverPct: 40,        // percent of cutter diameter per row
        grainDeg: 0,            // 0 = +X, 90 = +Y
        feedRateXY: 60,
        feedRateZ: 30,
        safeZ: 0.5,
        plungeFrom: "zero",
        plungeHeight: 0,
    },
};

// Increments for adjust operations. Tunable per param; pendant maps
// physical inputs (D-pad, wheel) onto these names.
var ADJUST_STEPS = {
    diameter: 0.0625,        // 1/16"
    depth: 0.0625,
    plungePerPass: 0.0625,
    cutterDiameter: 0.0625,
    feedRateXY: 5,           // IPM
    feedRateZ: 5,            // IPM
    plungeHeight: 0.0625,
    length: 0.25,
    angleDeg: 5,
    width: 0.25,
    stepoverPct: 5,
    grainDeg: 5,
};

// Hard bounds — prevent obvious bad inputs (negative diameter, etc.).
var BOUNDS = {
    diameter: [0.0625, 12],
    depth: [0.01, 4],
    plungePerPass: [0.01, 0.5],
    cutterDiameter: [0.0625, 1.0],
    feedRateXY: [5, 300],
    feedRateZ: [2, 150],
    plungeHeight: [-10, 10],
    length: [0.0625, 96],
    angleDeg: [0, 90],
    width: [0.0625, 96],
    stepoverPct: [5, 95],
    grainDeg: [0, 90],
};

function clamp(v, lo, hi) {
    if (v < lo) return lo;
    if (v > hi) return hi;
    return v;
}

function ToolboxController(machine) {
    EventEmitter.call(this);
    this.machine = machine;
    this.state = "idle";              // idle | active | executing
    this.cutType = "circular_bore";   // only one for the prototype
    this.params = Object.assign({}, DEFAULT_PARAMS[this.cutType]);
    this._lastTempFile = null;

    // While executing, watch machine state for return to idle so we
    // can transition back to "active" automatically.
    this._statusListener = this._onMachineStatus.bind(this);
    if (this.machine && typeof this.machine.on === "function") {
        this.machine.on("status", this._statusListener);
    }
}
util.inherits(ToolboxController, EventEmitter);

ToolboxController.prototype.close = function () {
    if (this.machine && typeof this.machine.removeListener === "function") {
        this.machine.removeListener("status", this._statusListener);
    }
};

ToolboxController.prototype._emitState = function (reason) {
    var payload = {
        state: this.state,
        cutType: this.cutType,
        params: Object.assign({}, this.params),
        reason: reason || null,
    };
    this.emit("toolbox_state", payload);
};

ToolboxController.prototype.toggle = function () {
    if (this.state === "executing") {
        log.debug("toolbox: toggle ignored, cut in progress");
        return;
    }
    if (this.state === "idle") {
        this.state = "active";
        log.info("toolbox: entered " + this.cutType + " mode; params=" +
                 JSON.stringify(this.params));
        this._emitState("enter");
    } else {
        this.state = "idle";
        log.info("toolbox: exited cut mode");
        this._emitState("exit");
    }
};

ToolboxController.prototype.adjustParam = function (name, delta) {
    if (this.state !== "active") {
        log.debug("toolbox: adjustParam ignored, state=" + this.state);
        return;
    }
    if (!(name in this.params)) {
        log.warn("toolbox: adjustParam unknown param '" + name + "'");
        return;
    }
    var step = ADJUST_STEPS[name];
    if (step === undefined) {
        log.warn("toolbox: adjustParam no step defined for '" + name + "'");
        return;
    }
    var newVal = this.params[name] + step * delta;
    var bound = BOUNDS[name];
    if (bound) newVal = clamp(newVal, bound[0], bound[1]);
    this.params[name] = Math.round(newVal * 10000) / 10000;  // snap to 4dp
    log.debug("toolbox: " + name + " = " + this.params[name]);
    this._emitState("adjust:" + name);
};

// String params have enumerated values rather than numeric bounds —
// reject anything not in the allowed set rather than passing garbage
// through to the generator.
var ENUM_VALUES = {
    mode: ["pocket", "perimeter"],
    direction: ["cw", "ccw"],
    plungeFrom: ["zero", "height"],
};

ToolboxController.prototype.setParam = function (name, value) {
    if (!(name in this.params)) return;
    var allowed = ENUM_VALUES[name];
    if (allowed) {
        if (allowed.indexOf(value) === -1) {
            log.warn("toolbox: setParam rejected '" + name + "'='" + value +
                     "' (not in " + JSON.stringify(allowed) + ")");
            return;
        }
    } else {
        var bound = BOUNDS[name];
        if (bound) value = clamp(value, bound[0], bound[1]);
    }
    this.params[name] = value;
    this._emitState("set:" + name);
};

// Swap the active cut type. Replaces the param set wholesale with the
// new type's defaults — cuts don't share param shapes (a straight line
// has length/angleDeg; a bore has diameter/mode/etc.) so trying to
// preserve old values would just produce nonsense for the new tool.
ToolboxController.prototype.setCutType = function (cutType) {
    if (this.state === "executing") {
        log.debug("toolbox: setCutType ignored, cut in progress");
        return;
    }
    if (!(cutType in DEFAULT_PARAMS)) {
        log.warn("toolbox: setCutType unknown '" + cutType + "'");
        return;
    }
    if (this.cutType === cutType) return;
    // Preserve operator-level settings that don't belong to any single
    // cut: the bit definition and the plunge-from choice. The cut-
    // specific params (diameter/length/angleDeg/etc.) reset to the new
    // cut's defaults since they don't translate across geometries.
    var carryOver = ["cutterDiameter", "plungePerPass",
                     "feedRateXY", "feedRateZ",
                     "plungeFrom", "plungeHeight", "safeZ"];
    var preserved = {};
    for (var i = 0; i < carryOver.length; i++) {
        var k = carryOver[i];
        if (this.params[k] !== undefined) preserved[k] = this.params[k];
    }
    this.cutType = cutType;
    this.params = Object.assign({}, DEFAULT_PARAMS[cutType], preserved);
    log.info("toolbox: cut type set to " + cutType);
    this._emitState("cutType:" + cutType);
};

ToolboxController.prototype.cancel = function () {
    if (this.state === "executing") {
        log.debug("toolbox: cancel ignored, cut in progress");
        return;
    }
    this.state = "idle";
    log.info("toolbox: cancelled");
    this._emitState("cancel");
};

ToolboxController.prototype._readCurrentPosition = function () {
    var st = this.machine && this.machine.status;
    if (!st) return null;
    var x = st.posx;
    var y = st.posy;
    var z = st.posz;
    if (x === undefined || y === undefined || z === undefined) return null;
    return { x: x, y: y, z: z };
};

ToolboxController.prototype.commit = function () {
    if (this.state !== "active") {
        log.warn("toolbox: commit ignored, state=" + this.state);
        return { ok: false, reason: "not_active" };
    }
    var pos = this._readCurrentPosition();
    if (!pos) {
        log.warn("toolbox: commit failed, no position available");
        return { ok: false, reason: "no_position" };
    }

    // Resolve startZ from the plungeFrom mode:
    //   "zero"   → absolute Z0 is the top of cut
    //   "height" → use the operator-supplied plungeHeight (the dashboard
    //              defaults this to current Z when the operator flips to
    //              this mode, so "do nothing else" = plunge from here)
    var startZ = (this.params.plungeFrom === "height")
        ? this.params.plungeHeight
        : 0;

    var generated;
    try {
        if (this.cutType === "circular_bore") {
            generated = cuts.circularBore(Object.assign({}, this.params, {
                center: { x: pos.x, y: pos.y },
                startZ: startZ,
            }));
        } else if (this.cutType === "straight_line") {
            generated = cuts.straightLine(Object.assign({}, this.params, {
                center: { x: pos.x, y: pos.y },
                startZ: startZ,
            }));
        } else if (this.cutType === "planer") {
            generated = cuts.planer(Object.assign({}, this.params, {
                center: { x: pos.x, y: pos.y },
                startZ: startZ,
            }));
        } else {
            throw new Error("unknown cut type: " + this.cutType);
        }
    } catch (e) {
        log.warn("toolbox: commit generation failed: " + e.message);
        return { ok: false, reason: "generation_failed", error: e.message };
    }

    // Write the G-code to a temp file and ask the machine to run it.
    // Using a temp file matches the macros path — the engine accepts a
    // file path via runFile() which goes through interlock pre-scan and
    // proper runtime hand-off.
    var tmpDir = path.join(os.tmpdir(), "fabmo-toolbox");
    try {
        if (!fs.existsSync(tmpDir)) fs.mkdirSync(tmpDir, { recursive: true });
    } catch (e) {
        log.warn("toolbox: tmp dir create failed: " + e.message);
        return { ok: false, reason: "tmpdir_failed", error: e.message };
    }
    var fname = path.join(tmpDir,
        "toolbox-" + this.cutType + "-" + Date.now() + ".nc");
    try {
        fs.writeFileSync(fname, generated.gcode.join("\n") + "\n");
    } catch (e) {
        log.warn("toolbox: tmp file write failed: " + e.message);
        return { ok: false, reason: "tmpfile_write_failed", error: e.message };
    }

    log.info("toolbox: committing " + this.cutType +
             " at (" + pos.x.toFixed(3) + ", " + pos.y.toFixed(3) +
             ") tmpFile=" + fname +
             " summary=" + JSON.stringify(generated.summary));

    this._lastTempFile = fname;
    this.state = "executing";
    // _awaitingRun suppresses the executing→active transition in
    // _onMachineStatus during the brief manual→idle window: when the
    // user was jogging, runAfterManualExit fires a status update with
    // state=idle before runFile has actually started, which would
    // otherwise look like "the cut finished instantly."
    this._awaitingRun = true;
    // Remember whether we displaced the user out of manual mode — if so,
    // _onMachineStatus drops them back into manual when the cut finishes
    // so the keypad they were jogging on stays available.
    this._reenterManualOnDone = (this.machine.status &&
                                 this.machine.status.state === "manual");
    this._emitState("commit");

    // Manual runtime owns the engine while jogging — a direct runFile
    // call from manual state throws "Cannot arm machine for runFile from
    // the manual state". Mirror the pendant macro flow: send manual exit,
    // wait for the state transition out of manual, then runFile.
    var self = this;
    actions.runAfterManualExit(this.machine, function () {
        try {
            // bypassInterlock=true: operator-driven canned move, same
            // privilege level as a pendant macro press.
            self.machine.runFile(fname, true);
            self._awaitingRun = false;
        } catch (e) {
            log.warn("toolbox: runFile failed: " + e.message);
            self._awaitingRun = false;
            self.state = "active";
            self._emitState("error:run_failed");
        }
    });
    return { ok: true, summary: generated.summary, file: fname };
};

ToolboxController.prototype._onMachineStatus = function (status) {
    if (this.state !== "executing") return;
    if (!status) return;
    // Suppress the transient idle that fires while we're waiting on
    // runAfterManualExit to fire runFile — that's not job completion.
    if (this._awaitingRun) return;
    // Machine drops back to "idle" when the file is done. The pendant
    // controller transitions back to "active" so the user can adjust
    // params + commit another cut without re-toggling mode.
    if (status.state === "idle") {
        this.state = "active";
        log.info("toolbox: execution complete");
        this._emitState("done");
        // If the cut was kicked off from manual mode (i.e. the user was
        // jogging on the keypad), drop them back into manual so the
        // keypad reappears and they can keep jogging without an extra
        // click. Skip if commit was triggered from idle / dashboard-only.
        if (this._reenterManualOnDone) {
            this._reenterManualOnDone = false;
            actions.manualEnter(this.machine, { hideKeypad: false });
        }
    }
};

module.exports = {
    create: function (machine) { return new ToolboxController(machine); },
    ToolboxController: ToolboxController,
    DEFAULT_PARAMS: DEFAULT_PARAMS,
    BOUNDS: BOUNDS,
    ADJUST_STEPS: ADJUST_STEPS,
};
